#!/bin/bash
# Cria os tickets [VIDEOPRO] no Linear via orca CLI (team GAB).
set -u
mk() {
  orca linear save-issue --team GAB --title "$1" --description "$2" --priority "$3" --json 2>&1 | grep -oE '"identifier":"[^"]*"|"url":"[^"]*"' | head -2 | tr '\n' ' '
  echo ""
}
mk "[VIDEOPRO] F0.1 — Secret scan + rotação de credenciais (.env.local.bak-with-auth) [G1]" "Gate G1. Ver docs/plan/fases/F0-FUNDACAO.md. Listar credenciais referenciadas no .env.local.bak-with-auth (1271 bytes, untracked no editor legado); DONO rotaciona cada uma; gitleaks nos 3 repos; resultado limpo é condição de entrada do monorepo." urgent
mk "[VIDEOPRO] F0.2 — Monorepo: subtree editor-legacy + archive [P8/P20]" "Base = higsfield (histórico já no repo). Importar histórico do editor legado (11 commits) via git subtree em vendor/editor-legacy/; branch archive/editor-legacy; remover remotion-kit; plano zod@3 + Tailwind 3→4 + 17 handlers params-async. Ver F0-FUNDACAO.md." high
mk "[VIDEOPRO] F0.3 — Spec EDL v1 (packages/edl, zod@3) + testes [G2]" "Contrato: frame único, schemaVersion/revision (lock otimista 409), fps racional, assetId, transitions (consome/estende), envelope áudio, markers, keyframes reservado; comandos atômicos com baseRevision; testes unitários. Ver F0-FUNDACAO.md." high
mk "[VIDEOPRO] F0.4 — Spike motor Revideo (multi-track/áudio/alpha/legenda word-level) [G8]" "1-2 dias com critério de morte escrito ANTES: render multi-track com áudio, alpha/overlay, legenda sincronizada por frame, tempo de render de fixture 30s. Reprovar = plano B Remotion+Automators (decisão pré-aprovada). Ver F0-FUNDACAO.md." urgent
mk "[VIDEOPRO] F0.5 — CI Ponytail (Biome/Testes/Snyk/Playwright) + esqueleto no ar" "Pipeline: lint+tsc+testes edl+render fixture; Snyk sem High/Critical; gitleaks; Playwright smoke; deploy preview Vercel com /api/health 200 (hash conferido). DoD do AGENTS.md seção 2." high
mk "[VIDEOPRO] F1 — Identidade & Segurança (auth motionpro reuso + RBAC + RLS + BYOK) [G3]" "Consumir motionpro: OAuth Google/GitHub + Magic Link (routes/oauth.js) + rota editor-session; workspaces/memberships RBAC; RLS fechada (setup.sql:106-108 hoje é using(true)); BYOK por request (matar singleton lib/fal/client.ts) + chave mestra HKDF versionada; quotas/audit/idempotência (claim atômico dispatch.ts). Ver F1-IDENTIDADE-SEGURANCA.md." high
mk "[VIDEOPRO] F2 — Vertical Slice do Editor (upload/EDL/timeline/preview/render) [G5]" "Upload signed URL R2 + resumable + ffprobe; tabela projects (edl jsonb + revision); timeline NOSSA V1/V2/A1/SUB (add/move/trim/split/remove, undo/redo); render worker via adapter; dashboard uso/gasto; notificações Resend (mock-first); custo por vídeo calculado (G5). Ver F2-VERTICAL-SLICE-EDITOR.md." high
mk "[VIDEOPRO] F3 — Captions (5 famílias golden + QA SSIM)" "Camada word-level no motor nosso; estilos: Box, Kinetic, Glitch, Moderna, Hormozi (ref: plugin-legendas/packs); seletor estilo/cor/fonte; QA SSIM >0,95 contra previews MP4 do CDN + humano; fonte webfont licenciável. Ver F3-CAPTIONS.md." medium
mk "[VIDEOPRO] F4 — IA + MCP (chat EDL + 6 tools + agente Reels) [G4]" "ChatPanel com comandos EDL atômicos (baseRevision) + dry-run/diff/aprovação; MCP v2: asset_upload, project_create, edl_get, edl_patch, render, status; token curto por usuário + scopes + aprovação p/ custo; paths restritos; agente Reels. Separar tools premiere_* como legado. Ver F4-IA-MCP.md." medium
mk "[VIDEOPRO] F5 — Templates (registry + rebuild 10 cenas + 5-10 novos)" "packages/templates registry versionado (schema zod); rebuild das 10 cenas (A_FullScreen..Boneco) no motor nosso; 5-10 novos de mogrts usados (filtro fonte webfont); QA SSIM; aplicar por UI e chat. Ver F5-TEMPLATES.md." medium
mk "[VIDEOPRO] F6 — Export (fila persistente + 3 formatos)" "Tabela renders; claim atômico; retry/backoff; cancel; progresso; jobs órfãos; 9:16/1:1/16:9 do mesmo EDL; custo por render no dashboard; observabilidade. Ver F6-EXPORT.md." medium
mk "[VIDEOPRO] F7 — Comercial (billing packs + domínio + métricas)" "Billing/entitlements reuso motionpro (Stripe + packs no JWT); domínio próprio + migração deploy; KPI dashboard; nota MIT do fork Revideo. Ver F7-COMERCIAL.md." medium
echo "FIM"
